sudo: require
services:
  - docker

before_install:
  - docker build -t sripathyk/docker-react -f Dockerfile.dev .

script:
  - docker run sripathyk/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: docker-react
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-1-790546918280"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:  
    secure: "$AWS_SECRET_KEY"
